# Generated by Django 5.2.8 on 2025-12-16 03:15

import graceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(max_length=20)),
                ('body_shape', models.CharField(max_length=30)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('image_type', models.CharField(choices=[('face', 'Face Image'), ('body', 'Body Image')], max_length=10)),
                ('image', models.ImageField(upload_to=graceapp.models.user_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('skin_tone', models.CharField(blank=True, max_length=20, null=True)),
                ('body_shape', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
