# Generated by Django 5.2.8 on 2025-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionrecommendation',
            name='face_shape',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='face_shape',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
